#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Info:
#   author:    Miroslav Vidovic
#   file:      web-search.sh
#   created:   24.02.2017.-08:59:54
#   revision:  ---
#   version:   1.0
# -----------------------------------------------------------------------------
# Requirements:
#   rofi
# Description:
#   Use rofi to search the web.
# Usage:
#   web-search.sh
# -----------------------------------------------------------------------------
# Script:

declare -A URLS

URLS=(
  ["duckduckgo"]="https://www.duckduckgo.com/?q="
  ["odysee"]="https://odysee.com/$/search?q="
  ["youtube"]="https://www.youtube.com/results?search_query="
  ["github"]="https://github.com/search?q="
  ["medium"]="https://medium.com/search?q="
  ["stackoverflow"]="http://stackoverflow.com/search?q="
  ["pkg.go.dev"]="https://pkg.go.dev/search?q="
  ["searchcode"]="https://searchcode.com/?q="
  ["superuser"]="http://superuser.com/search?q="
  ["wolfram-alpha"]="https://wolframalpha.com/input/?i="
  ["google"]="https://www.google.com/search?q="
  ["amazon"]="https://www.amazon.co.uk/s?k="
  ["wikipedia"]="https://en.wikipedia.org/w/index.php?search="
  ["dictionary"]="https://www.oxfordlearnersdictionaries.com/definition/english/pertinent?q="
)

# List for rofi
gen_list() {
    for i in "${!URLS[@]}"
    do
      echo "$i"
    done
}

main() {
  # Pass the list to rofi
  platform=$( (gen_list) | rofi -dmenu -matching fuzzy -no-custom -location 0 -p "Search > " )

  if [[ -n "$platform" ]]; then
    query=$( (echo ) | rofi  -dmenu -matching fuzzy -location 0 -p "Query > " )

    if [[ -n "$query" ]]; then
      url=${URLS[$platform]}$query
      # xdg-open "$url"
      qutebrowser --target window "$url"
    else
      exit
    fi

  else
    exit
  fi
}

main

exit 0
